// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/empty-state/Current.tsx": () => import("../components/mockups/empty-state/Current.tsx"),
  "./components/mockups/empty-state/Mono.tsx": () => import("../components/mockups/empty-state/Mono.tsx"),
  "./components/mockups/empty-state/Sans.tsx": () => import("../components/mockups/empty-state/Sans.tsx")
};
